// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASEihMgWDEnt9ED5BOEIH_kBvfOAM9xqw',
    appId: '1:821863078918:web:900bf113e148a4f275f787',
    messagingSenderId: '821863078918',
    projectId: 'openf-d4c57',
    authDomain: 'openf-d4c57.firebaseapp.com',
    storageBucket: 'openf-d4c57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VXkoUBJJ5mRO3fRaMTzjwYf10Lebc-Q',
    appId: '1:821863078918:android:2b80d6a90f99116775f787',
    messagingSenderId: '821863078918',
    projectId: 'openf-d4c57',
    storageBucket: 'openf-d4c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypIi3VQtFcfHoSbBUN402TLhSweJVpDY',
    appId: '1:821863078918:ios:f407f612c751ee6b75f787',
    messagingSenderId: '821863078918',
    projectId: 'openf-d4c57',
    storageBucket: 'openf-d4c57.firebasestorage.app',
    iosBundleId: 'com.example.openfoundry',
  );
}
